---
title: "Fire-Peerimeters-to-EqualArea"
author: "Anna Talucci"
date: "5/5/2021"
output: html_document
---

# Overview






# Clear workspace

```{r}
rm(list=ls()) 
```

# Packages

```{r include=FALSE}
library(sp)
library(sf)
library(rgdal) # geospatial data
library(raster)
library(rgeos) # GIS Geometry
library(foreign) # deals with dbf files
```

# Projection
[BC Albers Equal Area projection](https://georepository.com/crs_3005/NAD83-BC-Albers.html)

https://epsg.io/3005 or https://spatialreference.org/ref/epsg/3005/

```{r}
ea_bc = "+proj=aea +lat_1=50 +lat_2=58.5 +lat_0=45 +lon_0=-126 +x_0=1000000 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
```



# Read in Shapefile
```{r}
tw_perm = readOGR("../data/Fire-Perimeters-Original/tw_R10252_2013.shp", "tw_R10252_2013") 
```

```{r}
ch_perm = readOGR("../data/Fire-Perimeters-Original/ch_R10070_2014.shp", "ch_R10070_2014") 
```

```{r}
en_perm = readOGR("../data/Fire-Perimeters-Original/en_R10171_2012.shp", "en_R10171_2012") 
```

# Reproject in Equal area

```{r}
tw_perm_ea = spTransform(tw_perm, CRS(ea_bc))
ch_perm_ea = spTransform(ch_perm, CRS(ea_bc))
en_perm_ea = spTransform(en_perm, CRS(ea_bc))
```


# Convert to sf
```{r}
tw_rdnbr_sf = st_as_sf(tw_perm_ea)
ch_rdnbr_sf = st_as_sf(ch_perm_ea)
en_rdnbr_sf = st_as_sf(en_perm_ea)
```

#  Write to shapefile

```{r}
st_write(tw_rdnbr_sf, "../outputs/tw_R10252_2013_EA.shp", driver="ESRI Shapefile") 
st_write(ch_rdnbr_sf, "../outputs/ch_R10070_2014_EA.shp", driver="ESRI Shapefile") 
st_write(en_rdnbr_sf, "../outputs/en_R10171_2012_EA.shp", driver="ESRI Shapefile") 
```