---
title: "Raster-to-Polygon"
author: "Anna Talucci"
date: "5/5/2021"
output: html_document
---

# Overview

Perimeters initial process in Fire-perimeter script




# Clear workspace

```{r}
rm(list=ls()) 
```

# Packages

```{r include=FALSE}
library(sp)
library(sf)
library(rgdal) # geospatial data
library(raster)
library(rgeos) # GIS Geometry
library(foreign) # deals with dbf files
```

# Projection
[BC Albers Equal Area projection](https://georepository.com/crs_3005/NAD83-BC-Albers.html)

https://epsg.io/3005 or https://spatialreference.org/ref/epsg/3005/

```{r}
ea_bc = "+proj=aea +lat_1=50 +lat_2=58.5 +lat_0=45 +lon_0=-126 +x_0=1000000 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
```

# Read in raster
```{r}
tw_rdnbr = raster("../data/rdnbr/TW_rdnbr.tif")
```

```{r}
en_rdnbr = raster("../data/rdnbr/EN_rdnbr.tif")
```

```{r}
ch_rdnbr = raster("../data/rdnbr/CH_rdnbr.tif")
```
# Read in Shapefile
```{r}
tw_perm = readOGR("../data/perimeters/TweedsTreed.shp", "TweedsTreed") 
```

```{r}
en_perm = readOGR("../data/perimeters/EntiakoTreed.shp", "EntiakoTreed") 
```

```{r}
ch_perm = st_read("../data/perimeters/ChelaslieTreed.shp", "ChelaslieTreed") 
```

# Projection
```{r}
st_crs(ch_perm)
bc_crs=st_crs(ch_perm)
```


# Clip raster to polygon
```{r}
tw_clip <- mask(tw_rdnbr, tw_perm)
```

```{r}
en_clip <- mask(en_rdnbr, en_perm)
```

```{r}
ch_clip <- mask(ch_rdnbr, ch_perm)
```
# Plot

```{r}
plot(tw_clip)
plot(tw_perm, add=TRUE)
```

```{r}
plot(en_clip)
plot(en_perm, add=TRUE)
```

```{r}
plot(ch_clip)
plot(ch_perm, add=TRUE)
```

# Convert raster to polygon

```{r}
tw_rdnbr_poly = rasterToPolygons(tw_clip, fun=NULL, n=4, na.rm=TRUE, digits=12, dissolve=FALSE)

```

```{r}
en_rdnbr_poly = rasterToPolygons(en_clip, fun=NULL, n=4, na.rm=TRUE, digits=12, dissolve=FALSE)

```

```{r}
ch_rdnbr_poly = rasterToPolygons(ch_clip, fun=NULL, n=4, na.rm=TRUE, digits=12, dissolve=FALSE)

```

# Plot
```{r}
plot(tw_rdnbr_poly)
```

```{r}
plot(en_rdnbr_poly)
```

```{r}
plot(ch_rdnbr_poly)
```

# Convert to sf
```{r}
tw_rdnbr_sf = st_as_sf(tw_rdnbr_poly)
```

```{r}
en_rdnbr_sf = st_as_sf(en_rdnbr_poly)
```

```{r}
ch_rdnbr_sf = st_as_sf(ch_rdnbr_poly)
```

#  Write to shapefile

```{r}
st_write(tw_rdnbr_sf, "../outputs/RastertoPoly/tw_rdnnbr_poly.shp", driver="ESRI Shapefile") 
```

```{r}
st_write(en_rdnbr_sf, "../outputs/RastertoPoly/en_rdnnbr_poly.shp", driver="ESRI Shapefile") 
```

```{r}
st_write(ch_rdnbr_sf, "../outputs/RastertoPoly/ch_rdnnbr_poly.shp", driver="ESRI Shapefile") 
```